name: aurora_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.1
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  dartz: ^0.10.1
  shared_preferences: ^2.3.2
  build_runner: ^2.4.15
  flutter_screenutil: ^5.9.3
  json_annotation: ^4.9.0
  json_serializable: ^6.8.5
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.17
  modal_progress_hud_nsn: ^0.5.1
  either_dart: ^1.0.0
  provider: ^6.1.2
  get_it: ^8.0.2
  flutter_staggered_animations: ^1.1.1
  easy_stepper: ^0.8.5+1
  easy_autocomplete: ^1.6.0
  readmore: ^3.0.0
  font_awesome_flutter: ^10.9.1
  connectivity_plus: ^6.1.0
  pretty_dio_logger: ^1.4.0
  flutter_widget_from_html: ^0.15.0
  animate_do: ^4.2.0
  flutter_rating_bar: ^4.0.1
  go_router: ^16.2.1
  shimmer: ^3.0.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
        - asset: assets/fonts/Tajawal-Light.ttf
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/aurora_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
